languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://eshishkin.github.io/cv/"
title = "Eugene Shishkin - CV"
#googleAnalytics = ""


[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1
  [languages.ru]
    contentDir = 'content/ru'
    languageName = 'Russian'
    weight = 2



[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#e3bfb8"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#e3bfb8"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = true
